"""
lightweight.py — Aether-Blueprint v3.0
========================================
Neural Engine: GhostNet-based Mobile Specialist.

Responsibility:
    Encode/decode high-detail tiles (faces, text, unique features) using a
    lightweight auto-encoder designed for smartphone NPUs.

Architecture:
    Encoder:
        GhostConv stages (3 → 32 → 64 → 128 channels) with stride-2 downsampling
        Swin-Window Attention bottleneck at 8×8 spatial resolution
        Linear projection to latent_dim

    Decoder:
        Linear projection back from latent_dim
        3× GhostConv transpose stages (128 → 64 → 32 → 3)
        H-Swish activations throughout

Parameter budget:  < 0.5M parameters to fit mobile VRAM.

H-Swish: x * relu6(x + 3) / 6  (hardware-friendly, no exp())

OOM notes (incorporated from Stage 1 debugging):
    - The OOM crash was in dec_stage3's GhostConv during inplace relu6_.
      Inplace ops cause issues with the autograd graph on older CUDA drivers.
      All activations are now NON-inplace.
    - Decoder uses pixel-shuffle upsampling instead of ConvTranspose2d to
      avoid the large intermediate feature maps that blew T4 VRAM.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import math


# ──────────────────────────────────────────────────────────────────────────────
# Activations
# ──────────────────────────────────────────────────────────────────────────────

class HSwish(nn.Module):
    """H-Swish: x * relu6(x+3) / 6  — NON-inplace to prevent OOM on CUDA."""
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return x * F.relu6(x + 3.0) / 6.0          # inplace=False (default)


# ──────────────────────────────────────────────────────────────────────────────
# GhostConv
# ──────────────────────────────────────────────────────────────────────────────

class GhostConv(nn.Module):
    """
    Ghost Convolution: generate feature maps cheaply via a cheap linear transform.

    Produces `out_channels` feature maps using only `out_channels // ratio`
    primary convolutions; the rest are generated by a cheap depthwise conv.

    Args:
        in_ch    : input channels
        out_ch   : output channels (must be divisible by ratio)
        kernel   : primary conv kernel size
        stride   : primary conv stride
        ratio    : ghost ratio (default 2 → 50% primary, 50% ghost)
    """

    def __init__(self,
                 in_ch:   int,
                 out_ch:  int,
                 kernel:  int = 3,
                 stride:  int = 1,
                 ratio:   int = 2):
        super().__init__()
        primary_ch   = math.ceil(out_ch / ratio)
        cheap_ch     = out_ch - primary_ch
        padding      = kernel // 2

        self.primary_conv   = nn.Sequential(
            nn.Conv2d(in_ch, primary_ch, kernel, stride=stride,
                      padding=padding, bias=False),
            nn.BatchNorm2d(primary_ch),
            HSwish(),
        )
        self.cheap_operation = nn.Sequential(
            nn.Conv2d(primary_ch, cheap_ch, 3, stride=1, padding=1,
                      groups=primary_ch, bias=False),
            nn.BatchNorm2d(cheap_ch),
            HSwish(),
        ) if cheap_ch > 0 else nn.Identity()
        self.cheap_ch = cheap_ch

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x1 = self.primary_conv(x)
        if self.cheap_ch == 0:
            return x1
        x2 = self.cheap_operation(x1)
        return torch.cat([x1, x2], dim=1)


# ──────────────────────────────────────────────────────────────────────────────
# Swin-Window Attention (simplified, mobile-friendly)
# ──────────────────────────────────────────────────────────────────────────────

class SwinWindowAttention(nn.Module):
    """
    Local window self-attention (non-shifted, for bottleneck use).

    Args:
        dim        : channel dimension of input
        window_size: spatial window size (default 4)
        num_heads  : number of attention heads
    """

    def __init__(self, dim: int, window_size: int = 4, num_heads: int = 4):
        super().__init__()
        self.window_size = window_size
        self.num_heads   = num_heads
        head_dim         = dim // num_heads
        self.scale       = head_dim ** -0.5

        self.qkv  = nn.Linear(dim, dim * 3, bias=False)
        self.proj = nn.Linear(dim, dim)
        self.norm = nn.LayerNorm(dim)

    def _window_partition(self, x: torch.Tensor) -> torch.Tensor:
        """(B, H, W, C) → (B*nW, ws, ws, C)"""
        B, H, W, C = x.shape
        ws = self.window_size
        x  = x.view(B, H // ws, ws, W // ws, ws, C)
        x  = x.permute(0, 1, 3, 2, 4, 5).contiguous()
        return x.view(-1, ws, ws, C)

    def _window_reverse(self, windows: torch.Tensor, H: int, W: int) -> torch.Tensor:
        """(B*nW, ws, ws, C) → (B, H, W, C)"""
        ws = self.window_size
        B  = int(windows.shape[0] / (H * W / ws / ws))
        x  = windows.view(B, H // ws, W // ws, ws, ws, -1)
        x  = x.permute(0, 1, 3, 2, 4, 5).contiguous()
        return x.view(B, H, W, -1)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """x: (B, C, H, W)"""
        B, C, H, W = x.shape
        x_hwc = x.permute(0, 2, 3, 1)              # (B, H, W, C)

        windows   = self._window_partition(x_hwc)  # (B*nW, ws, ws, C)
        nW, ws, _, C_ = windows.shape
        win_flat  = windows.view(nW, ws * ws, C_)

        # QKV
        qkv = self.qkv(win_flat).reshape(nW, ws * ws, 3,
                                          self.num_heads,
                                          C_ // self.num_heads)
        qkv = qkv.permute(2, 0, 3, 1, 4)
        q, k, v = qkv.unbind(0)                    # (nW, nh, ws², hd)

        attn    = (q @ k.transpose(-2, -1)) * self.scale
        attn    = attn.softmax(dim=-1)
        out     = (attn @ v).transpose(1, 2).reshape(nW, ws * ws, C_)
        out     = self.proj(out)
        out     = self.norm(out + win_flat)         # residual + layer norm

        out_win = out.view(nW, ws, ws, C_)
        out_hwc = self._window_reverse(out_win, H, W)
        return out_hwc.permute(0, 3, 1, 2)         # (B, C, H, W)


# ──────────────────────────────────────────────────────────────────────────────
# Neural Engine
# ──────────────────────────────────────────────────────────────────────────────

class LightweightNeuralEngine(nn.Module):
    """
    GhostNet auto-encoder with Swin bottleneck.

    Target: < 0.5M parameters.

    Args:
        tile_size   (int): spatial size of input tiles.
        latent_dim  (int): bottleneck dimensionality.
        channels    (int): image channels (default 3).
    """

    def __init__(self,
                 tile_size:  int = 128,
                 latent_dim: int = 128,
                 channels:   int = 3):
        super().__init__()
        self.tile_size  = tile_size
        self.latent_dim = latent_dim

        # ── Encoder ────────────────────────────────────────────────────
        # 3 → 32 → 64 → 128, each halving spatial resolution
        self.enc_stage1 = GhostConv(channels, 32, kernel=3, stride=2)  # T/2
        self.enc_stage2 = GhostConv(32,       64, kernel=3, stride=2)  # T/4
        self.enc_stage3 = GhostConv(64,      128, kernel=3, stride=2)  # T/8

        bottle_spatial = tile_size // 8
        self.attention  = SwinWindowAttention(dim=128, window_size=4, num_heads=4)
        self.to_latent  = nn.Linear(128 * bottle_spatial * bottle_spatial, latent_dim)

        # ── Decoder ────────────────────────────────────────────────────
        self.from_latent = nn.Linear(latent_dim, 128 * bottle_spatial * bottle_spatial)
        self.bottle_size = bottle_spatial

        # Pixel-shuffle upsampling (avoids large ConvTranspose2d buffers)
        # ×2 upsample via pixel-shuffle with factor 2 (channels × 4)
        self.dec_stage3 = nn.Sequential(
            GhostConv(128, 128 * 4, kernel=3, stride=1),
            nn.PixelShuffle(2),                         # 128*4 ch → 128 ch, ×2 spatial
        )
        self.dec_stage2 = nn.Sequential(
            GhostConv(128, 64 * 4, kernel=3, stride=1),
            nn.PixelShuffle(2),
        )
        self.dec_stage1 = nn.Sequential(
            GhostConv(64, 32 * 4, kernel=3, stride=1),
            nn.PixelShuffle(2),
        )
        self.dec_out = nn.Conv2d(32, channels, kernel_size=1)

        self._init_weights()

    def _init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.ones_(m.weight)
                nn.init.zeros_(m.bias)
            elif isinstance(m, nn.Linear):
                nn.init.trunc_normal_(m.weight, std=0.02)
                if m.bias is not None:
                    nn.init.zeros_(m.bias)

    # ------------------------------------------------------------------
    # Encode
    # ------------------------------------------------------------------

    def encode(self, tiles: torch.Tensor) -> torch.Tensor:
        """
        Args:
            tiles: (N, C, T, T)
        Returns:
            latents: (N, latent_dim)
        """
        x = self.enc_stage1(tiles)
        x = self.enc_stage2(x)
        x = self.enc_stage3(x)
        x = self.attention(x)
        x = x.flatten(1)
        return self.to_latent(x)

    # ------------------------------------------------------------------
    # Decode
    # ------------------------------------------------------------------

    def decode(self, latents: torch.Tensor) -> torch.Tensor:
        """
        Args:
            latents: (N, latent_dim)
        Returns:
            tiles: (N, C, T, T)
        """
        N  = latents.shape[0]
        Bs = self.bottle_size
        x  = self.from_latent(latents).view(N, 128, Bs, Bs)
        x  = self.dec_stage3(x)    # → (N, 128, Bs*2, Bs*2)
        x  = self.dec_stage2(x)    # → (N,  64, Bs*4, Bs*4)
        x  = self.dec_stage1(x)    # → (N,  32, Bs*8, Bs*8)  = T
        x  = self.dec_out(x)
        return torch.sigmoid(x)    # (N, C, T, T) in [0,1]

    # ------------------------------------------------------------------
    # Forward (encode + decode for training)
    # ------------------------------------------------------------------

    def forward(self, tiles: torch.Tensor) -> torch.Tensor:
        latents = self.encode(tiles)
        return self.decode(latents)